services:
  vocab-pwa:
    build: .
    ports:
      - "30000:30000"
    environment:
      - NODE_ENV=production
      - PORT=30000
      - NEXT_PUBLIC_API_URL=https://api-koe.hieuintech.com/api
      - NEXT_PUBLIC_APP_URL=https://koe.hieuintech.com
    restart: unless-stopped
    container_name: vocab-pwa-app
