services:
  vocab-pwa:
    build: .
    ports:
      - "30000:30000"
    environment:
      - NODE_ENV=production
      - PORT=30000
      - NEXT_PUBLIC_API_URL=https://api-koe.091200.xyz/api
    restart: unless-stopped
    container_name: vocab-pwa-app